name: Austin Hackers Anonymous
title: Austin Hackers Academy
markdown: redcarpet
pygments: true
timezone: America/Chicago
homepage: index.html
meetingpage: meetings.html
aboutuspage: aboutus.html
mailinglistpage: mailinglist.html
ircpage: irc.html
redditpage: reddit.html
ourspawnpage: ourspawn.html
